version: '2.4'

services:

  redis:
    image: redis:5-alpine
    expose:
      - "6379"

  scopic:
    build: .
    env_file:
      - .env
    image: scopic:local
    ports:
      - 8000:8000
    volumes:
      - ./:/app/scopic_task
    command: python manage.py runserver 0.0.0.0:8000

  worker:
    image: scopic:local
    env_file:
      - .env
    volumes:
      - ./:/app/scopic_task
    command: celery -A scopic_task worker --loglevel=info -E
    depends_on:
      - scopic
      - redis

  celery_flower:
    image: scopic:local
    volumes:
      - ./:/app/scopic_task
    env_file:
      - .env
    ports:
      - 127.0.0.1:9999:5555
    command: celery flower -A scopic_task
    depends_on:
      - redis