# Generated by Django 3.0.5 on 2021-07-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_auto_20210708_2246'),
        ('api', '0002_auto_20210708_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userautobidding',
            name='product',
        ),
        migrations.AddField(
            model_name='userautobidding',
            name='product',
            field=models.ManyToManyField(to='home_page.Product'),
        ),
    ]
