# Generated by Django 3.0.5 on 2021-07-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210708_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userautobidding',
            name='product',
        ),
        migrations.AddField(
            model_name='bidshistory',
            name='auto_bid',
            field=models.BooleanField(default=False),
        ),
    ]
