# Generated by Django 3.2.5 on 2021-07-08 12:15

from django.db import migrations, models
import home_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_product_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='close_date',
            field=models.DateTimeField(default=home_page.models.set_close_date),
        ),
    ]
